#!/usr/bin/env python3
import os
import sys


def main():
    if 2 > len(sys.argv):
        return False
    if "sop-autoupdate" == sys.argv[1]:
        from autoupdate import main as autoupdatemain
        autoupdatemain()
    elif "trigger-sopupdate" == sys.argv[1]:
        from cron_trigger_autoupdate import trigger_autoupdate
        trigger_autoupdate()


if __name__ == '__main__':
    main()
